export type Lang = 'zh' | 'en';
export type Copy = Record<Lang, string>;
export const companyIdentity = {
  philosophy: {
    zh: '欢迎你带着自己的想法，一起探索前沿世界。',
    en: 'Bring your ideas. Explore the frontier with us.',
  } satisfies Copy,
  values: {
    zh: '让更多人的声音，进入关于未来的讨论。',
    en: 'Let more voices join the conversation about the future.',
  } satisfies Copy,
  status:
    'Claire selected 3A and 3B and approved website update on 2026-09-05; English translation',
};
export type PodcastPlatform = { label: Copy; url: string };
export const shows = [
  {
    slug: 'claire-and-friends',
    name: 'Claire & Friends',
    image: '/images/claire-and-friends.png',
    intro: {
      zh: '人一开口，时代就有了细节。',
      en: 'The world comes into focus when people speak.',
    },
    description: {
      zh: 'Claire 和身边的人聊聊。',
      en: 'Conversations with the people around Claire.',
    },
    kind: { zh: '人物访谈', en: 'Conversations' },
    copyStatus: 'Public tagline; transcript-backed description 2026-09-05',
    source: 'https://www.xiaoyuzhoufm.com/podcast/6a8161aeda2a63e7cbee35f3',
    platformLinks: [
      {
        label: { zh: '小宇宙节目页', en: 'Xiaoyuzhou show page' },
        url: 'https://www.xiaoyuzhoufm.com/podcast/6a8161aeda2a63e7cbee35f3',
      },
    ] as PodcastPlatform[],
    verifiedEpisodeCount: 0 as number | null,
  },
  {
    slug: 'frontier-talks',
    name: 'Frontier Talks',
    image: '/images/frontier-talks.png',
    intro: {
      zh: '对话 AI 时代真正做事的人。',
      en: 'Conversations with people building in the AI era.',
    },
    description: {
      zh: '从 AI、创业、商业和投资聊起，和嘉宾一起追问他们的判断、选择与实践。可以是两个人的深度对谈，也可以是多人圆桌。',
      en: 'Conversations about AI, entrepreneurship, business, and investing. Claire explores the judgments, choices, and work of her guests through one-on-one interviews and roundtables.',
    },
    kind: { zh: '访谈与圆桌', en: 'Interviews & roundtables' },
    copyStatus:
      'Claire chat 2026-09-01 + public platform 2026-09-05; English draft',
    source: 'https://www.xiaoyuzhoufm.com/podcast/6a76db3b9e288de7d50c8630',
    platformLinks: [
      {
        label: { zh: '小宇宙节目页', en: 'Xiaoyuzhou show page' },
        url: 'https://www.xiaoyuzhoufm.com/podcast/6a76db3b9e288de7d50c8630',
      },
    ] as PodcastPlatform[],
    verifiedEpisodeCount: 0 as number | null,
  },
  {
    slug: 'rabbit-hole',
    name: 'Rabbit Hole',
    image: '/images/rabbit-hole.png',
    intro: { zh: '顺着好奇心往下走。', en: 'Think out loud with Claire.' },
    description: {
      zh: '这是我的个人独白，聊我对这个世界的思考。我会顺着一个线索，不断深入、下钻、发散，最后可能想出一些很有意思的东西，也可能没有。',
      en: 'My solo podcast about how I see the world. I follow a thread, dig deeper, and branch out. I might end up with something interesting, or I might not.',
    },
    kind: { zh: '个人独白', en: 'Solo' },
    copyStatus: 'Claire direct 2026-09-05; English draft',
    source: 'https://www.xiaoyuzhoufm.com/podcast/66f1314525a55603dfa0d368',
    platformLinks: [
      {
        label: { zh: '小宇宙节目页', en: 'Xiaoyuzhou show page' },
        url: 'https://www.xiaoyuzhoufm.com/podcast/66f1314525a55603dfa0d368',
      },
    ] as PodcastPlatform[],
    verifiedEpisodeCount: 0 as number | null,
  },
] as const;
export const articles = [
  {
    date: '2026.08.18',
    title: {
      zh: 'GPT-5.6 Sol 1M 上下文向 ChatGPT 账号开放',
      en: 'GPT-5.6 Sol’s 1M context opens to ChatGPT accounts',
    },
    url: 'https://signals.frontierworld.ai/2026/08/18/codex-gpt56-sol-1m-context/',
    image:
      'https://signals.frontierworld.ai/2026/08/18/codex-gpt56-sol-1m-context/og.png',
    summary: {
      zh: 'OpenAI 工程师 Tibo 称，Codex 的 GPT-5.6 Sol 1M 配置现已支持 ChatGPT 账号用量。',
      en: 'OpenAI engineer Tibo says Codex’s GPT-5.6 Sol 1M configuration now supports ChatGPT account usage.',
    },
  },
  {
    date: '2026.08.16',
    title: {
      zh: 'Claude Agent 组成团队后，开始串通和互相攻击',
      en: 'Claude agents collude and attack one another in team tests',
    },
    url: 'https://signals.frontierworld.ai/2026/08/16/anthropic-multiagent-coordination/',
    image:
      'https://signals.frontierworld.ai/2026/08/16/anthropic-multiagent-coordination/og.png',
    summary: {
      zh: 'Anthropic 的多 Agent 压力测试出现价格串通、资源拥堵和相互破坏。',
      en: 'Anthropic’s multi-agent stress tests found price collusion, resource congestion, and sabotage.',
    },
  },
  {
    date: '2026.08.15',
    title: {
      zh: 'Claude 要给文字加水印了，AI 写作还能藏住吗？',
      en: 'Claude is getting text watermarks. Can AI writing stay hidden?',
    },
    url: 'https://signals.frontierworld.ai/2026/08/15/claude-text-watermark/',
    image:
      'https://signals.frontierworld.ai/2026/08/15/claude-text-watermark/og.png',
    summary: {
      zh: 'Anthropic 将给未来 Claude 模型生成的文本加入水印。',
      en: 'Anthropic plans to add watermarks to text generated by future Claude models.',
    },
  },
] as const;
export const navigation = [
  { path: 'signals', label: { zh: '观察', en: 'Signals' } },
  { path: 'products', label: { zh: '产品', en: 'Products' } },
  { path: 'work', label: { zh: '合作', en: 'Work' } },
  { path: 'open', label: { zh: '开放', en: 'Open' } },
  { path: 'about', label: { zh: '关于', en: 'About' } },
  { path: 'foundation', label: { zh: '基金会', en: 'Foundation' } },
] as const;
export const footerSections = [
  {
    path: 'signals',
    label: { zh: '观察', en: 'Signals' },
    links: [
      {
        path: 'signals#latest',
        label: { zh: '最新文章', en: 'Latest articles' },
      },
      { path: 'signals#topics', label: { zh: '专题', en: 'Topics' } },
      {
        path: 'signals#method',
        label: { zh: '编辑方法', en: 'Editorial approach' },
      },
    ],
  },
  {
    path: 'products',
    label: { zh: '产品', en: 'Products' },
    links: [
      { path: 'products', label: { zh: '产品概览', en: 'Overview' } },
      { path: 'podcasts', label: { zh: '播客', en: 'Podcasts' } },
      { path: 'products#courses', label: { zh: '课程', en: 'Courses' } },
      { path: 'products#events', label: { zh: '活动', en: 'Events' } },
    ],
  },
  {
    path: 'work',
    label: { zh: '合作', en: 'Work' },
    links: [
      {
        path: 'work#collaborations',
        label: { zh: '合作方向', en: 'Collaborations' },
      },
      { path: 'work#cases', label: { zh: '项目与案例', en: 'Projects' } },
      { path: 'work#contact', label: { zh: '联系', en: 'Contact' } },
    ],
  },
  {
    path: 'open',
    label: { zh: '开放', en: 'Open' },
    links: [
      { path: 'open#projects', label: { zh: '开放项目', en: 'Projects' } },
      { path: 'open#docs', label: { zh: '使用文档', en: 'Documentation' } },
      { path: 'open#updates', label: { zh: '更新', en: 'Updates' } },
    ],
  },
  {
    path: 'about',
    label: { zh: '关于', en: 'About' },
    links: [
      {
        path: 'about#brand',
        label: { zh: 'Frontier World', en: 'Frontier World' },
      },
      { path: 'about#claire', label: { zh: 'Claire', en: 'Claire' } },
      { path: 'about#team', label: { zh: '团队', en: 'Team' } },
      { path: 'about#principles', label: { zh: '原则', en: 'Principles' } },
    ],
  },
  {
    path: 'foundation',
    label: { zh: '基金会', en: 'Foundation' },
    links: [
      { path: 'foundation#mission', label: { zh: '使命', en: 'Mission' } },
      {
        path: 'foundation#priorities',
        label: { zh: '关注方向', en: 'Priorities' },
      },
      { path: 'foundation#programs', label: { zh: '项目', en: 'Programs' } },
      {
        path: 'foundation#participation',
        label: { zh: '参与方式', en: 'Get involved' },
      },
      {
        path: 'foundation#organization',
        label: { zh: '组织信息', en: 'Organization' },
      },
      { path: 'foundation#updates', label: { zh: '动态', en: 'Updates' } },
    ],
  },
] as const;
export function route(lang: Lang, path = '') {
  return `${lang === 'en' ? '/en' : ''}/${path}`.replace(/\/$/, '') || '/';
}
export const sourceCheckedAt = '2026-09-05';
